language: python
branches:
  except:
    - legacy
    - experimental
env:
  - TOXENV=py27
  - TOXENV=py34
before_install:
  - git clone https://code.google.com/p/plowshare
  - cd plowshare; sudo make install
install:
  - travis_retry pip install -e '.[test]'
addons:
  postgresql: '9.3'
script:
  - tox
