language: python
branches:
  except:
    - legacy
    - experimental
env:
  - TOXENV=py27
  - TOXENV=py34
before_install:
  - git clone https://code.google.com/p/plowshare; cd plowshare; sudo make install; cd ../
  - git clone https://github.com/Storj/plowshare-wrapper.git; cd plowshare-wrapper; sudo pip install .; cd ../ 
install:
  - travis_retry pip install -e '.[test]'
addons:
  postgresql: '9.3'
script:
  - tox
