language: python
branches:
  except:
    - legacy
    - experimental
env:
  - TOXENV=py27
  - TOXENV=py34
before_install:
  - wget https://plowshare.googlecode.com/files/plowshare4_1~git20140112.7ad41c8-1_all.deb
  - sudo dpkg -i plowshare4_1~git20140112.7ad41c8-1_all.deb
  - sudo apt-get -f install
install:
  - travis_retry pip install -e '.[test]'
addons:
  postgresql: '9.3'
script:
  - tox
